name: Puppeteer Test
 
on:
  push:
    branches: [ main ]
 
jobs:
  puppeteer-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
 
    - name: Install Puppeteer Dependencies
      run: npm install puppeteer
 
    - name: Puppeteer Test
      run: node test.js
