name: Puppeteer Test
 
on:
  push:
    branches:
      - main
  watch:
    types: started
  schedule:
    - cron: 0 0 1 * *
 
jobs:
  puppeteer-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
 
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '16.x'
 
    - name: Install Puppeteer Dependencies
      run: npm install puppeteer
 
    - name: Puppeteer Test
      run: node test.js
